server:  
  port: 8072

spring:
  application:
    name: task
  datasource:
      url: jdbc:mysql://47.94.196.111:3306/iac?useUnicode=true&characterEncoding=utf8&useSSL=false
      name:
      username: root
      password: 2111
      dbcp2:
          max-idle: 10

      hikari:
          data-source-properties:

              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
          idle-timeout: 60000

          connection-timeout: 60000

  redis:
    database: 0
    host: 47.94.196.111
    password: 111
    port: 6379


logging:
  level:
    root: info












